# -*- coding: utf-8 -*-
"""
/***************************************************************************
 vectors2raster
                                 A QGIS plugin
 Rasterize and Overlay analysis that not affected by NODATA settings

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-27
        copyright            : (C) 2024 by Kwanhyun, Kim
        email                : popyj01012@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load vectors2raster class from file vectors2raster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vectors2raster import vectors2raster
    return vectors2raster(iface)
