# -*- coding: utf-8 -*-
"""
/***************************************************************************
 vectors2rasterDialog
                                 A QGIS plugin
 Rasterize and Overlay analysis that not affected by NODATA settings

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Kwanhyun, Kim
        email                : popyj01012@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import *

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'vectors2raster_dialog_base.ui'))


class vectors2rasterDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(vectors2rasterDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        #set default values and filter
        self.spbRasterPixelSize.setRange(1,1000)
        self.spbRasterPixelSize.setValue(50)
        self.progressBar.setValue(0)
        self.outputFileWidget.setFilter("TIF Files(*.tif)|*.tif;; TIFF Files(*.tiff)|*.tiff")
